#!/bin/bash
#
# Create assets in BQ for a new client, given a unique identifier

if [ $# -ne 1 ]; then
    echo "😰  Expected client name!"
    exit 1
fi

DATASET=$1
TABLE=stat
REPLACER=s/%CLIENT%/$DATASET/g
VIEW_SQL=$( sed $REPLACER < clustered.sql)

bq mk $DATASET
bq mk --schema schema.json -t $DATASET.$TABLE
bq mk --nouse_legacy_sql --view="$VIEW_SQL" $DATASET.stat_clustered
